FROM datasyntax/ubuntu-base
LABEL maintainer = "Ross Ivantsiv <ross@datasntax.ua>"

RUN apt-get update && \
apt-get -y --no-install-recommends install bzip2 git && \
apt-get clean

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash







